---
- name: HAProxy playbook
  become: yes
  gather_facts: yes
  hosts: loadbalancer
  tasks:
    - name: Install HAProxy
      yum: name={{ item }} state=present
      with_items:
        - haproxy
      notify: restart_haproxy

    - name: Create HAProxy config for webservers
      template: src=../templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644

    - name: Enable syslog UDP logging
      lineinfile: dest=/etc/rsyslog.conf
                  line="$ModLoad imudp\n$UDPServerRun 514"
                  insertafter=EOF

    - name: Enable syslog logging for HAProxy
      lineinfile: dest=/etc/rsyslog.d/haproxy.conf
                  line="local2.*                       /var/log/haproxy.log"
                  insertafter=EOF
                  create=yes
      notify: restart_rsyslog

  handlers:
    - name: restart_haproxy
      service: name=haproxy state=restarted enabled=yes

    - name: restart_syslog
      service: name=rsyslog state=restarted enabled=yes